#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : softflowd
Version  : v1.1.0
Release  : 1
URL      : https://github.com/irino/softflowd/archive/refs/tags/softflowd-v1.1.0.tar.gz
Source0  : https://github.com/irino/softflowd/archive/refs/tags/softflowd-v1.1.0.tar.gz
Summary  : Network traffic analyser capable of Cisco NetFlow data export
Group    : Development/Tools
License  : BSD-2-Clause
Requires: softflowd-bin = %{version}-%{release}
Requires: softflowd-license = %{version}-%{release}
Requires: softflowd-man = %{version}-%{release}
BuildRequires : libpcap-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
softflowd is a software implementation of a flow-based network traffic
monitor.  softflowd reads network traffic and gathers information about
active traffic flows.  A "traffic flow" is communication between two IP
addresses or (if the overlying protocol is TCP or UDP) address/port tuples.
The intended use of softflowd is as a software implementation of Cisco’s
NetFlow traffic account system.  softflowd supports data export using
versions 1, 5 or 9 of the NetFlow protocol.

%package bin
Summary: bin components for the softflowd package.
Group: Binaries
Requires: softflowd-license = %{version}-%{release}

%description bin
bin components for the softflowd package.


%package license
Summary: license components for the softflowd package.
Group: Default

%description license
license components for the softflowd package.


%package man
Summary: man components for the softflowd package.
Group: Default

%description man
man components for the softflowd package.


%prep
%setup -q -n softflowd-softflowd-v1.1.0
cd %{_builddir}/softflowd-softflowd-v1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1675707216
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1675707216
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/softflowd
cp %{_builddir}/softflowd-softflowd-%{version}/COPYING %{buildroot}/usr/share/package-licenses/softflowd/a9fc57ad8bef9bb07c97162e24f86e95e1f55fd6 || :
cp %{_builddir}/softflowd-softflowd-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/softflowd/a9fc57ad8bef9bb07c97162e24f86e95e1f55fd6 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/softflowctl
/usr/bin/softflowd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/softflowd/a9fc57ad8bef9bb07c97162e24f86e95e1f55fd6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/softflowctl.8
/usr/share/man/man8/softflowd.8
